begin;

create extension if not exists pg_trgm;

create table public.employees (
    id text primary key,
    name text not null,
    dept text not null,
    location text not null,
    joined_year integer not null,
    entry_type text not null,
    available_slots text[],
    interests_public boolean not null default true,
    slots_public boolean not null default true,
    is_admin boolean not null default false,
    constraint employees_id_format_check
        check (id ~ '^E[0-9]{3}$'),
    constraint employees_location_check
        check (location in ('東京', '大阪')),
    constraint employees_entry_type_check
        check (entry_type in ('新卒', '中途', '異動')),
    constraint employees_available_slots_check
        check (
            available_slots is null
            or available_slots <@ array[
                '平日夜', '土曜午前', '土曜午後', '日曜'
            ]::text[]
        )
);

create table public.activities (
    id integer generated by default as identity primary key,
    name text not null,
    category text not null,
    constraint activities_category_check
        check (category in ('スポーツ', 'ゲーム', 'ウェルネス', '文化・趣味'))
);

create table public.employee_interests (
    employee_id text not null references public.employees (id),
    activity_id integer not null references public.activities (id),
    level text not null,
    constraint employee_interests_employee_activity_key
        unique (employee_id, activity_id),
    constraint employee_interests_level_check
        check (level in ('未経験', '初心者', '経験あり'))
);

create table public.clubs (
    id integer generated by default as identity primary key,
    name text not null,
    icon text,
    activity_id integer not null references public.activities (id),
    location text not null,
    slot text not null,
    schedule_note text,
    frequency text not null,
    level text not null,
    fact_adult_starters text not null,
    mood_tags text[],
    message text,
    fee text not null,
    fee_note text,
    rental text not null,
    belongings_note text,
    join_leave text not null,
    after_activity text not null,
    organizer_id text not null references public.employees (id),
    is_active boolean not null default true,
    updated_at timestamptz not null default now(),
    constraint clubs_location_check
        check (location in ('東京', '大阪')),
    constraint clubs_slot_check
        check (slot in ('平日夜', '土曜午前', '土曜午後', '日曜')),
    constraint clubs_frequency_check
        check (frequency in ('毎週', '月2回', '月1回', '不定期')),
    constraint clubs_level_check
        check (level in ('初心者歓迎', 'レベル問わず', '経験者向け')),
    constraint clubs_fact_adult_starters_check
        check (fact_adult_starters in ('多い', '少しいる', 'いない')),
    constraint clubs_mood_tags_count_check
        check (mood_tags is null or cardinality(mood_tags) <= 3),
    constraint clubs_mood_tags_values_check
        check (
            mood_tags is null
            or mood_tags <@ array[
                'ゆるめ', 'しっかり練習', '黙々と集中',
                'わいわい賑やか', 'おしゃべり多め', '少人数'
            ]::text[]
        ),
    constraint clubs_fee_check
        check (fee in ('無料', '500円以下', '1,000円以下', 'それ以上')),
    constraint clubs_rental_check
        check (rental in ('あり', 'なし')),
    constraint clubs_join_leave_check
        check (join_leave in ('OK', 'できれば最初から', '要相談')),
    constraint clubs_after_activity_check
        check (after_activity in ('なし', 'ランチ・お茶', '飲み会', '日による'))
);

create table public.club_members (
    club_id integer not null references public.clubs (id),
    employee_id text not null references public.employees (id),
    joined_at date,
    constraint club_members_club_employee_key
        unique (club_id, employee_id)
);

create table public.events (
    id integer generated by default as identity primary key,
    club_id integer not null references public.clubs (id),
    event_date date not null,
    start_time time not null,
    end_time time not null,
    meeting_place text not null,
    meeting_time time,
    status text not null default '予定',
    constraint events_status_check
        check (status in ('予定', '中止')),
    constraint events_time_order_check
        check (end_time > start_time)
);

create table public.applications (
    id integer generated by default as identity primary key,
    event_id integer not null references public.events (id),
    applicant_id text not null references public.employees (id),
    status text not null default '申込済み',
    is_first_time boolean not null,
    applied_at timestamptz not null default now(),
    canceled_at timestamptz,
    confirmed_at timestamptz,
    constraint applications_status_check
        check (status in ('申込済み', 'キャンセル')),
    constraint applications_canceled_at_check
        check (status <> 'キャンセル' or canceled_at is not null)
);

create table public.messages (
    id integer generated by default as identity primary key,
    application_id integer not null references public.applications (id),
    sender_id text not null references public.employees (id),
    body text not null,
    sent_at timestamptz not null default now(),
    constraint messages_body_not_blank_check
        check (btrim(body) <> '')
);

create table public.notifications (
    id integer generated by default as identity primary key,
    recipient_id text not null references public.employees (id),
    type text not null,
    application_id integer references public.applications (id),
    event_id integer references public.events (id),
    body text not null,
    created_at timestamptz not null default now(),
    read_at timestamptz,
    constraint notifications_type_check
        check (type in ('申込', 'キャンセル', 'メッセージ', 'スタンプ', '中止')),
    constraint notifications_body_not_blank_check
        check (btrim(body) <> '')
);

create table public.action_logs (
    id integer generated by default as identity primary key,
    employee_id text not null references public.employees (id),
    action text not null,
    club_id integer references public.clubs (id),
    conditions jsonb,
    created_at timestamptz not null default now(),
    constraint action_logs_action_check
        check (action in ('search_club', 'view_club', 'apply')),
    constraint action_logs_shape_check
        check (
            (action = 'search_club' and conditions is not null)
            or (action = 'view_club' and club_id is not null)
            or action = 'apply'
        )
);

create index employees_dept_location_idx
    on public.employees (dept, location);

create index employee_interests_employee_id_idx
    on public.employee_interests (employee_id);

create index employee_interests_activity_id_idx
    on public.employee_interests (activity_id);

create index activities_name_trgm_idx
    on public.activities using gin (name gin_trgm_ops);

create index clubs_active_location_slot_idx
    on public.clubs (is_active, location, slot);

create index club_members_club_id_idx
    on public.club_members (club_id);

create index events_club_date_idx
    on public.events (club_id, event_date);

create index applications_event_applicant_idx
    on public.applications (event_id, applicant_id);

create unique index applications_one_active_per_employee_idx
    on public.applications (event_id, applicant_id)
    where status = '申込済み';

create index messages_application_id_idx
    on public.messages (application_id);

create index notifications_recipient_read_idx
    on public.notifications (recipient_id, read_at);

create index action_logs_employee_created_idx
    on public.action_logs (employee_id, created_at desc);

commit;
